# Generated by Django 2.1.4 on 2019-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_templates_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='templates',
            name='submit',
            field=models.TextField(),
        ),
    ]
