# Generated by Django 2.1.4 on 2019-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190904_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='endpoint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='selection',
            name='url',
            field=models.TextField(),
        ),
    ]
