# Generated by Django 2.1.4 on 2019-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190904_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='keyId',
            field=models.CharField(default='event_id', max_length=100),
        ),
    ]
