# Generated by Django 2.1.4 on 2019-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_selection_keyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='keyId',
            field=models.CharField(max_length=100),
        ),
    ]
