# Generated by Django 2.1.4 on 2019-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190923_1307'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='eventmaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sportsmaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='businessId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='uuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selection',
            name='keyId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='selection',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sportsmaster',
            name='uuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='templates',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
