# Generated by Django 2.1.4 on 2019-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190927_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('businessId', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('price', models.IntegerField()),
                ('isPublished', models.BooleanField()),
                ('isDisabled', models.BooleanField()),
                ('isDeleted', models.BooleanField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=100)),
                ('sportsId', models.CharField(max_length=100)),
                ('tf', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='contentId',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityMaster',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('businessId', models.CharField(max_length=100)),
                ('minPrice', models.IntegerField()),
                ('maxPrice', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=100)),
                ('sportsId', models.CharField(max_length=100)),
                ('tf', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('storeId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
