# Generated by Django 2.1.4 on 2019-09-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_classmaster_classsport_contentid_facilitymaster_facilitysport_storedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventsport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilitysport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
