# Generated by Django 2.1.4 on 2019-09-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190927_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmaster',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='classmaster',
            name='lng',
        ),
    ]
