# Generated by Django 2.1.4 on 2019-09-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190927_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitymaster',
            name='maxPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facilitymaster',
            name='minPrice',
            field=models.FloatField(default=0),
        ),
    ]
