# Generated by Django 2.1.4 on 2019-09-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190927_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilitySport',
        ),
    ]
