# Generated by Django 2.1.4 on 2019-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_facilitysport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.CharField(max_length=100)),
                ('sportsId', models.CharField(max_length=100)),
                ('tf', models.BooleanField(default=True)),
            ],
        ),
    ]
