# Generated by Django 2.1.4 on 2019-09-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_contentid_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentid',
            name='sport',
            field=models.CharField(max_length=100),
        ),
    ]
