# Generated by Django 2.1.4 on 2019-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190930_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='notAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='businessId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='selection',
            name='keyId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportsmaster',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportsmaster',
            name='group',
            field=models.CharField(max_length=200),
        ),
    ]
