# Generated by Django 2.1.4 on 2019-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190930_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentid',
            name='classtype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
