# Generated by Django 2.1.4 on 2019-09-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_contentid_classtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmaster',
            old_name='price',
            new_name='minPrice',
        ),
    ]
