# Generated by Django 2.1.4 on 2019-11-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191127_2044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sportsmaster',
            table='sportsmaster',
        ),
    ]
