# Generated by Django 2.1.4 on 2019-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20191127_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='sportbtn',
        ),
        migrations.AddField(
            model_name='contentid',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
