# Generated by Django 2.1.4 on 2019-11-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20191128_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selection',
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
