# Generated by Django 2.1.4 on 2019-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20191128_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('keyId', models.CharField(max_length=100)),
                ('location', models.BooleanField()),
                ('check', models.BooleanField(default=False)),
                ('url', models.TextField()),
                ('endpoint', models.CharField(default='', max_length=200)),
                ('notAvailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typeof', models.CharField(max_length=20)),
                ('sportbtn', models.TextField()),
                ('location', models.TextField()),
                ('userid', models.TextField()),
                ('check', models.TextField(default='')),
                ('submit', models.TextField()),
            ],
        ),
    ]
